# Generated by Django 5.2.4 on 2025-07-08 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_by', models.CharField(default='Member_only_story', max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('thought', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('post_img', models.ImageField(blank=True, null=True, upload_to='post_img/')),
                ('full_thought', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('title', 'thought', 'full_thought')},
            },
        ),
    ]
