# Generated by Django 5.2.4 on 2025-07-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='full_thought',
            new_name='description',
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('title', 'thought', 'description')},
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Member_only_story', max_length=100),
        ),
        migrations.RemoveField(
            model_name='post',
            name='story_by',
        ),
    ]
